### ISSUE TITLE
Multi-monitor requires passing of the --geometry argument to mpv as well

### ISSUE THREAD

**Issue by mixolydianmel** [ujjwal96/xwinwrap#14]
The `-g WxH+X+Y` option in `xwinwrap` seems to be useless, at least for my use case where I have two monitors and want to duplicate the animated background on both, each with different resolutions.
Using the `-g` option seemed to have little to no effect on the geometry of the actual display, and it would just stretch the video across both monitors.
Maybe something to do with `xinerama`?

Anyway, the solution was to use the `--geometry` flag in `mpv` and run `xwinwrap` twice, once for each monitor.
Posting this here so other people can see.

**Comment by MiraiMindz** [comment]
How do you managed to do that?

I'm struggling to put an GIF as wallpaper, I'm on ArchLinux with i3-WM my monitor setup is ( 1: 1366x768 | 2: 1280x1024)

**Comment by norawibb** [comment]
Yeah I am using this with streamlink and the -g option does nothing. The player runs right in the middle of my two monitors no matter what I do. However, I can't try this suggestion because I am unable to add flags to mpv without it just failing altogether.
`streamlink https://www.youtube.com/watch?v=5qap5aO4i9A best --player="xwinwrap -ov -fs -- "mpv --geometry=1920x1080" -cache 4096 -quiet -loop 0 -wid WID"`
This is probably due to the nested quotes, but I tried changing the inner ones to ' and it still failed with no useful error.
